#!/usr/bin/env bash
# loop 4th bad luck 8th good luck 

i=0

while [ $i -lt 11 ]; do
    if [ $i = 4 ];
    then
        echo "bad luck"
    elif [ $i = 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
