#!/usr/bin/env bash
# loop 4th bad luck 8th good luck 

i=1

while [ $i -le 11 ];
do
       if [ $i -eq 4 ];
        then
	    echo "bad luck"
	  elif [ $i -eq 8 ];
	  then
	 echo "good luck"
	else
	   echo "Best School"
	   fi
	i=$((i+1))
	done
