#!/usr/bin/env bash
# loop 4th bad luck 8th good luck 

i=0

while [ $i -lt 9 ]; do
    if [ $i = 3 ];
    then
        echo "bad luck"
    elif [ $i = 7 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
