#!/usr/bin/env bash
# process and pid file
touch "/var/run/myscript.pid" > "$BASHPID"
while true
do
	echo 'To infinity and beyond'
	trap 'echo I hate the kill command ; rm $file ; exit ' SIGTERM 
	trap 'echo Y U no love me?! ; rm $file ; exit ' SIGINT
done

